# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - 'testci'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  first_job:
    name: test job
    runs-on: windows-latest
    steps:
      - name: hello
        run: |
          "hi"
